### ISSUE TITLE
报名帖

### ISSUE THREAD

**Issue by phodal** [phodal/growth2#1]
麻烦填写下以下的信息哈：

昵称: ID
GitHub:
角色: Dev / PM / UX /BA 等等
擅长技术栈: JavaScript / Ionic /Android /iOS 等等
期望学习点：如TS，Angluar 2等等
其他爱好：。。

如:

昵称: Phodal
GitHub: [http://github.com/phodal](http://github.com/phodal)
角色：发起人
擅长技术栈：JavaScript / Python / Java / Node.js
期望学习点：用户增长
其他爱好：《文明5》玩家

顺便加一个这个微信号：growth-ren （注明：参与Growth开发哈）

**Comment by haoflynet** [comment]
First Blood

**Comment by song-what** [comment]
昵称: Song
GitHub: https://github.com/song-what
角色: Dev / UX
擅长技术栈：HTML / CSS / 网页设计
期望学习点：Ionic & Angluar.js & Node.js & ios
其他爱好：不想当厨子的UX不是好前端，学习中。。。旅行中。。。折腾中。。。

**Comment by phodal** [comment]
@haoflynet @song-what 顺便加一个这个微信号：growth-ren （注明：参与Growth开发哈）

**Comment by willshion** [comment]
昵称willshion
GitHub/willshion
擅长JS，前端，ng2
学习 fullstuck
爱好LOL

**Comment by zhangmx** [comment]
昵称: 纯黑烈焰
GitHub: https://github.com/zhangmx
角色: Dev/PM
擅长技术栈:  PHP / JavaScript / java
期望学习点: ionic，angluar ， 项目管理
其他爱好: 烹饪（东北菜），唱歌

**Comment by Mezy** [comment]
昵称: Mezy
GitHub: https://github.com/mezy
角色: Dev
擅长技术栈: HTML / CSS / JavaScript
期望学习点: Angular 2，React Native，Node.js
其他爱好: 音乐，等待《骑马与砍杀2》

**Comment by jk77me** [comment]
昵称: jk77
GitHub: https://github.com/jk77me
角色: Dev
擅长技术栈: iOS / JavaScript
期望学习点: Angular 2，React Native，Node.js
其他爱好: 守望屁股

**Comment by sydeEvans** [comment]
昵称: sydeEvans
GitHub:https://github.com/sydeEvans
角色: Dev 
擅长技术栈: JavaScript / Ionic / Angular /Typescript / Nodejs
期望学习点：Angluar 2,
其他爱好：DOTA2 , 守望先锋，玩山地车~

**Comment by mmaoyu** [comment]
昵称: mmaoyu
GitHub:https://github.com/mmaoyu
角色: Dev 
擅长技术栈: Java/JavaScript /Php/
期望学习点：Spark/钢琴
其他爱好：羽毛球/股票

**Comment by xuzongbao** [comment]
昵称: Elven_xu
GitHub: https://github.com/xuzongbao
角色：Dev
擅长技术栈：JavaScript / Java / Bootstrap / JQuery
期望学习点：全站发展
其他爱好：钓鱼、炉石传说

**Comment by ReynoK** [comment]
昵称: Rey
GitHub: https://github.com/ReynoK
角色：Dev
擅长技术栈：PHP/Python/HTML+CSS(略懂)
期望学习点：Full Stack Developer
其他爱好：看书，健身，游泳，ACG，宅）

**Comment by XueShaozhe** [comment]
昵称: skipxmao10
GitHub: https://github.com/XueShaozhe
角色：UX
擅长技术栈：界面设计/用户体验
期望学习点：前端/app开发/用户增长
其他爱好：everything about Tech and Sports

**Comment by peterchinzhen** [comment]
昵称: Petrez
GitHub: https://github.com/peterchinzhen
角色：Dev
擅长技术栈：Java / Typescript / Javascript
期望学习点：AngularJS 2 / ionic / iOS
其他爱好：吃 / 电影 / 旅游

**Comment by Toscl** [comment]
昵称: Toscl
GitHub: https://github.com/toscl
Git: http://igit.toscl.com/git
角色：Dev
擅长技术栈：PHP/ Python/ Javascript/ JAVA/ Linux 运维
期望学习点：负载均衡 / 推荐算法 / nodejs
其他爱好：电影 / 乒乓球 / LOL

**Comment by btcioner** [comment]
昵称: 谢大炮
GitHub: https://github.com/btcioner
角色：Dev
擅长技术栈：Java / Typescript / Angular2
期望学习点： ionic 
其他爱好：看书

**Comment by leejianyang** [comment]
昵称: Hansen
GitHub: https://github.com/leejianyang
角色: Dev
擅长技术栈: Python / PHP
期望学习点：前端 / 单元测试
其他爱好：足球
