### ISSUE TITLE
返回顶端按钮随页面一起滚动

### ISSUE THREAD

**Issue by Detachment** [phodal/growth2#5]
![default](https://cloud.githubusercontent.com/assets/11611875/16869175/140232b8-4aae-11e6-8136-482f7479bcdb.jpg)
#### 图中右侧箭头（返回顶端按钮）会随着页面的滚动而滚动，一般来说应该是固定定位吧~

**Comment by phodal** [comment]
@Detachment 这个按钮被我删了。好像是没必要的
