### ISSUE TITLE
增加一个复制链接的功能

### ISSUE THREAD

**Issue by qinzhongjie** [phodal/growth2#9]
新版思路清晰，页面简洁，不错不错！
用的时候发现“练手项目”上面的项目地址，每次都要看着往电脑上敲，要是旁边能有个复制键就好了。
![图片](http://120.76.130.118/source/Screenshot_2016-07-30-16-19-47-726_growth.ren.png)

**Comment by phodal** [comment]
@qinzhongjie OK，这个问题在考虑了。我原本想的是点击可以直接打开，看来可以加上两个相应的按钮。

**Comment by phodal** [comment]
fixed it
